name = "onboarding-builder2"
main = "index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
# GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET should be set in .dev.vars for local development
# and as environment variables in Cloudflare Workers for production
# JWT_SECRET should be set in .dev.vars for local development
# and as environment variables in Cloudflare Workers for production


# Production database (old schema - commented out)
# [[d1_databases]]
# binding = "DB"
# database_name = "onboarding-builder"
# database_id = "83620845-c9d9-4eec-bdc7-97f687f742fc"

# Development database for versioning features (correct schema)
[[d1_databases]]
binding = "DB"
database_name = "onboarding-builder-versions-dev"
database_id = "96dcdb6b-ecbc-464d-92e7-45634918f631"

[build]
command = "npm run build"

# Development server configuration
[dev]
port = 8787

# Assets configuration for static files
[assets]
directory = "./dist"
binding = "ASSETS"
